---
- name: Install config chrony within timesyncd
  hosts: ubuntu_lab_hosts
  become: true
  gather_facts:  false
  vars:
    ansible_user: ubuntu-usr
    ansible_become_password: 'QWEqwe123!@#'
    #  vars_files:
    # - vault.yml
  tasks:
    - name: Disable timesync
      service:
        name: systemd-timesyncd.service
        state: stopped
        enabled: false
    - name:  install chrony
      apt:
        name:  chrony
        state:  latest
    - name: Write chrony config
      template:
        src: ./roles/templates/chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
        backup: yes
      notify: restart chronyd

  handlers:
    - name: restart chronyd
      service:
        name: chronyd
        state: restarted
